language:
  - python

python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-package thanatos --cover-erase --with-doctest

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b02cabf6ccb21d2984da
    on_success: change
    on_failure: always
    on_start: false
