language:
  - python

python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-package sacrud_deform --cover-erase --with-doctest

after_success:
  - coveralls
